# Generated by Django 5.1.7 on 2025-03-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='current_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='İşlem sonrası ana stokta kalan miktar', null=True),
        ),
    ]
