# Generated by Django 5.1.7 on 2025-03-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stocktransaction_current_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='current_receiver_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Transfer işleminde alıcının stoğundaki miktar', null=True),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='current_user_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='İşlem sonrası kullanıcının stoğundaki miktar', null=True),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='current_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='İşlem sonrası ana stok miktarı', null=True),
        ),
    ]
