# Generated by Django 5.1.7 on 2025-03-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stocktransaction_current_receiver_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_limit',
            field=models.PositiveIntegerField(default=1, help_text='Ürün miktarı bu değerin altına düşerse kritik stok durumu oluşur.'),
        ),
    ]
