# Generated by Django 5.1.7 on 2025-03-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_min_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order_placed',
            field=models.BooleanField(default=False, help_text='Bu ürün için sipariş çekildiyse True olur.'),
        ),
    ]
