# Generated by Django 5.1.7 on 2025-03-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(default='test@example.com', help_text='Kritik stok raporu bu mail adresine gönderilecek.', max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='min_limit',
            field=models.PositiveIntegerField(default=0, help_text='Bu değer 0 ise ürün adedi 0 olduğunda kritik stok sayılır. Eğer 5 gibi bir değer girilirse ürün adedi 5 veya altına düştüğünde kritik stok sayılır.'),
        ),
    ]
