# Generated by Django 5.1.7 on 2025-03-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_appsettings_alter_product_min_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appsettings',
            name='recipient_email',
        ),
        migrations.AddField(
            model_name='appsettings',
            name='critical_stock_email',
            field=models.EmailField(default='kritik@example.com', help_text='Kritik stok raporu bu mail adresine gönderilecek.', max_length=254),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='export_stock_email',
            field=models.EmailField(default='export@example.com', help_text='Tüm stok raporu bu mail adresine gönderilecek.', max_length=254),
        ),
    ]
