# Generated by Django 5.1.7 on 2025-03-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_stocktransaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'Ana Stok Girişi'), ('UPDATE', 'Ana Stok Güncelleme'), ('TAKE', 'Kullanıcının Ana Stoktan Alması'), ('RETURN', 'Kullanıcının Ana Stoka İade Etmesi'), ('TRANSFER', 'Kullanıcılar Arası Transfer'), ('USE', 'Kullanım'), ('ADJUST', 'Admin Stok Ayarı'), ('O_TRANSFER', 'Diğer Transfer')], max_length=10),
        ),
    ]
